//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLAT.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FLAT.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axiom.
        /// </summary>
        internal static string Axiom {
            get {
                return ResourceManager.GetString("Axiom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t compute first, invalid grammar..
        /// </summary>
        internal static string ComputeFirstException {
            get {
                return ResourceManager.GetString("ComputeFirstException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of configurations.
        /// </summary>
        internal static string Configurations {
            get {
                return ResourceManager.GetString("Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar&apos;s table have conflict, can&apos;t create parser..
        /// </summary>
        internal static string ConflictException {
            get {
                return ResourceManager.GetString("ConflictException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  can&apos;t be empty..
        /// </summary>
        internal static string EmptyException {
            get {
                return ResourceManager.GetString("EmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammar.
        /// </summary>
        internal static string Grammar {
            get {
                return ResourceManager.GetString("Grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown tokens or invalid order of tokens..
        /// </summary>
        internal static string InvalidTokensException {
            get {
                return ResourceManager.GetString("InvalidTokensException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one axiom production. Use extension method GrammarExtensions.ExtendGramamar..
        /// </summary>
        internal static string MoreThanOneAxiomProduction {
            get {
                return ResourceManager.GetString("MoreThanOneAxiomProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to move mark in configuration out of production..
        /// </summary>
        internal static string MoveMarkOutOfProduction {
            get {
                return ResourceManager.GetString("MoveMarkOutOfProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No productions described axiom in productions set..
        /// </summary>
        internal static string NoAxiomInProductionsException {
            get {
                return ResourceManager.GetString("NoAxiomInProductionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nonterminal.
        /// </summary>
        internal static string Nonterminal {
            get {
                return ResourceManager.GetString("Nonterminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No productions described nonterminals: .
        /// </summary>
        internal static string NoProductionsForNonterminalsException {
            get {
                return ResourceManager.GetString("NoProductionsForNonterminalsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  doesn&apos;t contain end marker..
        /// </summary>
        internal static string NoStringEndMarker {
            get {
                return ResourceManager.GetString("NoStringEndMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of symbols on stack is less than argument..
        /// </summary>
        internal static string NotEnoughToPopException {
            get {
                return ResourceManager.GetString("NotEnoughToPopException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  can&apos;t be null..
        /// </summary>
        internal static string NullException {
            get {
                return ResourceManager.GetString("NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of states in table can&apos;t be less than 1..
        /// </summary>
        internal static string NumberOfStatesLessThanOneException {
            get {
                return ResourceManager.GetString("NumberOfStatesLessThanOneException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of parse-tree node.
        /// </summary>
        internal static string ParseTreeNodeName {
            get {
                return ResourceManager.GetString("ParseTreeNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production&apos;s set.
        /// </summary>
        internal static string Productions {
            get {
                return ResourceManager.GetString("Productions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State not found in table..
        /// </summary>
        internal static string StateNotFoundException {
            get {
                return ResourceManager.GetString("StateNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicitly setted symbol name.
        /// </summary>
        internal static string SymbolName {
            get {
                return ResourceManager.GetString("SymbolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol not found in table..
        /// </summary>
        internal static string SymbolNotFoundException {
            get {
                return ResourceManager.GetString("SymbolNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection of symbols.
        /// </summary>
        internal static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersection of terminals set and nonterminals set is not empty..
        /// </summary>
        internal static string TerminalAndNonterminalSetsIntersectExciption {
            get {
                return ResourceManager.GetString("TerminalAndNonterminalSetsIntersectExciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token&apos;s name.
        /// </summary>
        internal static string TokenName {
            get {
                return ResourceManager.GetString("TokenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens collection.
        /// </summary>
        internal static string Tokens {
            get {
                return ResourceManager.GetString("Tokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected empty symbol in list with length &gt; 1..
        /// </summary>
        internal static string UnexpectedEmptySymbolException {
            get {
                return ResourceManager.GetString("UnexpectedEmptySymbolException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
